### ISSUE TITLE
BO - Unable to find template

### ISSUE THREAD

**Issue by duGuillaume** [dediagency/sylius-seo-plugin#11]
Hello, 

Here a new bug, sry :'(

I've this error in admin when i go to products (list/add/edit) / Channel  (add/edit) / Taxons (list/add/edit)

`Unable to find template "@DediSyliusSEOPlugin/Resources/views/Admin/SEO/form_block_type.html.twig" (looked into: /var/www/html/vendor/dedi/sylius-seo-plugin/src/Resources/views).`

In `src/DependencyInjection/DediSyliusSEOExtension.php`
replace
`'@DediSyliusSEOPlugin/Resources/views/Admin/SEO/form_block_type.html.twig',`
by 
`'@DediSyliusSEOPlugin/Admin/SEO/form_block_type.html.twig',`

Symfony 5 / Sylius 1.9

Thanks.

**Comment by enpepet** [comment]
As a workaround you can create the file on templates (or in your theme)

templates/bundles/DediSyliusSEOPlugin/Resources/views/Admin/SEO/form_block_type.html.twig

**Comment by kevinbalicot** [comment]
Hello !

Can you try again with the last version please ? :)
