### ISSUE TITLE
Rich Snippet usage for Product and Taxon entities

### ISSUE THREAD

**Issue by duGuillaume** [dediagency/sylius-seo-plugin#12]
Hello,

Here my bug of the day, sry,

When i follow the install doc in

```
class Product
    ....
    public function getRichSnippetSubjectParent()

```
getRichSnippetSubjectParent must be compatible with interface RichSnippetSubjectInterface
so we replace by `public function getRichSnippetSubjectParent(): ?self`

But this function return a Taxon and not a Product so we have this error

`Return value of App\Entity\Product\Product::getRichSnippetSubjectParent() must be an instance of App\Entity\Product\Product or null, instance of Proxies\__CG__\App\Entity\Taxonomy\Taxon returned`

Thanks

**Comment by kevinbalicot** [comment]
Hello ! 

Maybe with this signature

```php
public function getRichSnippetSubjectParent(): ?RichSnippetSubjectInterface
```

It's will work fine :)
