### ISSUE TITLE
Template overriding 

### ISSUE THREAD

**Issue by Loocos** [dediagency/sylius-seo-plugin#15]
Hello,

Little issue about template overriding. We cannot use template or theme overide through our projects. 
We can only use Sylius event in order to override any of the plugin templates.

I mean, I need to override the sylius event and the block path template. We shouldn't do that.
We should do that following the documentation : https://docs.sylius.com/en/1.9/customization/template.html

Template event should be transformed from : 
DediSyliusSEOPlugin:Shop/Header:_title.html.twig 

To : 
@DediSyliusSEOPlugin/Shop/Header/_title.html.twig

Thanks in advance

**Comment by Loocos** [comment]
Change ui.yaml : 
`sylius_ui:
    events:
        dedi_sylius_seo_plugin.metatags:
            blocks:
                dedi_seo_metatags: '@DediSyliusSEOPlugin/Shop/Header/_metatags.html.twig'
        dedi_sylius_seo_plugin.title:
            blocks:
                dedi_seo_title: '@DediSyliusSEOPlugin/Shop/Header/_title.html.twig'
        dedi_sylius_seo_plugin.rich_snippets:
            blocks:
                dedi_seo_metatags: '@DediSyliusSEOPlugin/Shop/Header/_richSnippets.html.twig'

        # Layout
        sylius.shop.layout.head:
            blocks:
                dedi_seo_head_google_tracking: '@DediSyliusSEOPlugin/Shop/Header/_googleTracking.html.twig'
        sylius.shop.layout.before_body:
            blocks:
                dedi_seo_body_google_tracking: '@DediSyliusSEOPlugin/Shop/Body/_googleTracking.html.twig'

        # Channel Admin
        sylius.admin.channel.create.form:
            blocks:
                dedi_seo_channel: '@DediSyliusSEOPlugin/Admin/Channel/Form/_seo.html.twig'

        sylius.admin.channel.update.form:
            blocks:
                dedi_seo_channel: '@DediSyliusSEOPlugin/Admin/Channel/Form/_seo.html.twig'
`

**Comment by kevinbalicot** [comment]
Hello !

Can you try again with the last version please ? :)

**Comment by FlorentinGarnier** [comment]
It's ok for me. We can override template in theme
