### ISSUE TITLE
Make it compatible with symfony 5

### ISSUE THREAD

**Issue by GalloisLuca** [dediagency/sylius-seo-plugin#17]
!!  PHP Fatal error:  Declaration of Dedi\SyliusSEOPlugin\DataCollector\RichSnippetsDataCollector::collect(Symfony\Component\HttpFoundation\Request $request, Symfony\Component\HttpFoundation\Response $response) must be compatible with Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface::collect(Symfony\Component\HttpFoundation\Request $request, Symfony\Component\HttpFoundation\Response $response, ?Throwable $exception = NULL) in source/vendor/dedi/sylius-seo-plugin/src/DataCollector/RichSnippetsDataCollector.php on line 22

For the error message the solution is something like that : 

Before : 

`public function collect(Request $request, Response $response)`

After : 

`public function collect(Request $request, Response $response, \Throwable $exception = null)`

**Comment by kevinbalicot** [comment]
Hello !

Can you try again with the last version please ? :)

**Comment by Roshyo** [comment]
FWIW, I just installed and it is running under Symfony 5.4.2 :)
