### ISSUE TITLE
Unable to save product SEO fields

### ISSUE THREAD

**Issue by bellu** [dediagency/sylius-seo-plugin#23]
Sylius Version: 1.10.0
Symfony Version: 5.3.9

I've installed the plugin on my Sylius shop, and when i try to save some SEO values in the product page; i got the Sylius message "Product Updated".

But in my DB there's nothing saved in the tables.

How can i solve this?

**Comment by JulienLoison** [comment]
CI runs and tests on #55 shows no problem with saving data in DB
