### ISSUE TITLE
Offers price invalid for Google Search Console

### ISSUE THREAD

**Issue by pierre-vassoilles** [dediagency/sylius-seo-plugin#38]
Hi ! 

Google Search Console says the price format is invalid for my products, probably for product variant price.
In HTML source, the variant price is formatted with a coma and I think Google expects a dot as separator : 

![image](https://user-images.githubusercontent.com/6613517/161243757-da51afab-412b-4635-b7d6-90eff86eb86c.png)

![image](https://user-images.githubusercontent.com/6613517/161243156-014b5d5b-b79f-4c25-abf3-d299e0291ca8.png)

Is there a solution ?

PS:  My default locale is fr_FR, it may explains that problem...

**Comment by JulienLoison** [comment]
Fixed with https://github.com/dediagency/sylius-seo-plugin/pull/46, see https://github.com/dediagency/sylius-seo-plugin/releases/tag/v2.0.1
