### ISSUE TITLE
Error in INSTALL.md

### ISSUE THREAD

**Issue by paulvscode** [dediagency/sylius-seo-plugin#63]
Hello !

There is an error in the INSTALL.md file, at the section : "Rich Snippet usage for Product and Taxon entities".

It says to implement the "RichSnippetSubjectInterface" to product and taxon when it should be : "RichSnippetProductSubjectInterface".

(if I understood properly).

Cheers!

Edit: here is the error I get: 
![image](https://github.com/dediagency/sylius-seo-plugin/assets/67148083/7f70cb8b-70af-45d9-9542-1fc328f78c90)

**Comment by FlorentinGarnier** [comment]
#61 <= see this PR
