### ISSUE TITLE
Fatal error - Declaration must be compatible

### ISSUE THREAD

**Issue by duGuillaume** [dediagency/sylius-seo-plugin#9]
Hello, 

Here a missmatch declaration

` Declaration of Dedi\SyliusSEOPlugin\DataCollector\RichSnippetsDataCollector::collect(Symfony\Component\HttpFoundation\Request $request, Symfony\Component\HttpFoundation\Response $response) must be compatible with Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface::collect(Symfony\Component\HttpFoundation\Request $request, Symfony\Component\HttpFoundation\Response $response, ?Throwable $exception = NULL) in /var/www/html/vendor/dedi/sylius-seo-plugin/src/DataCollector/RichSnippetsDataCollector.php on line 22`
 
 should be fix by:
` public function collect(Request $request, Response $response, \Throwable $exception = null)`
 
 Sylius 1.9
 Symfony 5
 
 Best regards

**Comment by sersilva** [comment]
Same problem here.
Would be great to have a fix.
Thanks for your work!
Kind regards.
